const TRANSACTION_STATUS = {
    PENDING: "pending",
    SUCCESS: "successful",
    FAILED: "failed",
    REVERSED: "reversed"
};

const WALLET_TYPES = {
    CREDIT: "credit",
    DEBIT: "debit"
};

const PAYMENT_SOURCES = {
    PAYSTACK: "PAYSTACK",
    WALLET: "WALLET",
    REFUND: "REFUND",
    REFERRAL: "REFERRAL"
};

const SERVICES = {
    WALLET_FUNDING: "WALLET_FUNDING",
    AIRTIME: "AIRTIME",
    DATA: "DATA",
    ELECTRICITY: "ELECTRICITY",
    CABLE_TV: "CABLE_TV",
    TRANSFER: "TRANSFER",
    REFERRAL_BONUS: "REFERRAL_BONUS"
};

const REFERRAL_STATUS = {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED"
};

const KYC_STATUS = {
    PENDING: "PENDING",
    VERIFIED: "VERIFIED",
    REJECTED: "REJECTED"
};

module.exports = {
    TRANSACTION_STATUS,
    WALLET_TYPES,
    PAYMENT_SOURCES,
    SERVICES,
    REFERRAL_STATUS,
    KYC_STATUS
};